Fix nightly version for MIPS cross-compilation.
MIPS has moved to tier 3, we need the nightly version for
cross-compilation to this target. To avoid this, I reverted back to
1.74.1 (latest version with MIPS toolchain pre-compiled), however this
re-introduces #52. Currently the latest nightly version returns an error
during build:

 undefined reference to `pthread_getname_np'